#!/usr/bin/env python3

import sys

from PyQt5 import QtWidgets

from inspigtor.gui.main_window import MainWindow

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)

    window = MainWindow()

    sys.exit(app.exec_())
